travis:
  secure:
    BINSTAR_TOKEN: vTp4fWFauBvM1PJXi2f+FQ3qAfQiuvdeajYmohEhi1ayGqw6bkb2kmOMLA2vd3GgxjYR9Q4QrRVwXsdWxivsysdedU5leQiQd3KurvlWlsXlPBbIvz98PqDWkQhxasiV3JcDOAl2MWIK2FtpjAzzGJGYj1MLodnJna+VJOZ+eJmCi2AtxeoHmRkkpvBt9RO7ybO3RKMb33LwIz7W6XEaEfke5lHlr8B3iZvvBIPYxWzzciiJAIIb8iMdiMpsDL/L2LhPZPPtLV7lN4kA0zMuU30wG59MIywPXa+7qEnwaii1mb349Ckxvc3qMJtfxSlitpQVsHTDYChENawTNBDvzKBnA+TuSDIKc4zTmPWQNVcFa38KXS8vR/cYVDuJ8Xs0K4bqz8K1b0bFmlKvU4tilJo9UNW1da3kOw6FtWs+pxBZ+tDAaOlzt4gQ3tXozEfGnoxPbSU2gndTp/zrFZTLy3UOsoCJs9N17/tShUOZtp7fMeAJi+Fo/AWSl1p71zEYk7A2zaG+JIN1y2GqUbpLujn7SqSkrMwyIY3qodrRizug+4NGIPlMTrk8+oUsikZNfUaM0nZ6eJV+87uJmClnvYwBzcCCgoRO6xyJP6XpUNnpZUX8o5nb5wDCSyEkdhUUIfey73h/8DMYO9KirNFm2AgaA2iX8TNpOTBh/bDRsgg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
